[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["Simon Siegler <simon.siegler@1und1.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.1"